### ISSUE TITLE
(2.0) If generation

### ISSUE THREAD

**Issue by MicroNovaX** [ton-blockchain/intellij-ton#104]
I propose to change the code generation logic when writing "if" and make it similar to Java, due to the fact that at the moment automatic closing of conditions only creates additional problems.
![idea64_9YS3kLI8Ix](https://github.com/ton-blockchain/intellij-ton/assets/23459010/a228e573-72ea-42a7-a347-a705885ae6ac)

**Comment by andreypfau** [comment]
The current logic is implemented in such a way that in FunC (as in Rust/Go, for example), the condition can be any expression that does not have to be enclosed in parentheses. So auto-completion doesn't insert them
