### ISSUE TITLE
(2.0) Include assist

### ISSUE THREAD

**Issue by MicroNovaX** [ton-blockchain/intellij-ton#108]
I suggest adding help writing #include suggesting possibly relevant files for the user.
I also suggest adding a highlight if the include is not used and suggestions for using functions from neighboring .fc files, with the automatic addition of the #include line.

![idea64_ZhWPMUekpk](https://github.com/ton-blockchain/intellij-ton/assets/23459010/23df0d1f-0b17-4843-bd92-bd6f0d16cc32)

![idea64_NVtrOStu6G](https://github.com/ton-blockchain/intellij-ton/assets/23459010/e7225266-10fb-4a5f-bd10-862f08aeba28)

**Comment by andreypfau** [comment]
Added in 2.1.0
