### ISSUE TITLE
Global variables and constants declared in including files aren't found

### ISSUE THREAD

**Issue by NickNekilov** [ton-blockchain/intellij-ton#113]
There are two files:

- `imports/op-codes.fc` (with `const op::burn = 0x595f07bc;`)
- `wallet.fc` (uses `op::burn`)

IDE highlights `op::burn` in `wallet.fc` as an unknown identifier:

![Screenshot from 2023-08-07 18-31-06](https://github.com/ton-blockchain/intellij-ton/assets/97469315/5e9aa166-babd-4c6e-bc9f-acdf9d4e36f6)

**Comment by alijawan** [comment]
1172
