### ISSUE TITLE
IDE doesn't allow renaming an identifier if it contains ":"

### ISSUE THREAD

**Issue by NickNekilov** [ton-blockchain/intellij-ton#114]
![image](https://github.com/ton-blockchain/intellij-ton/assets/97469315/01eb5cf3-382c-48f5-83c1-0cb21739b754)

**Comment by RAFI7708** [comment]
> ![image](https://github.com/ton-blockchain/intellij-ton/assets/97469315/01eb5cf3-382c-48f5-83c1-0cb21739b754)
