### ISSUE TITLE
[v2.0] no highlighting of standard library methods

### ISSUE THREAD

**Issue by ilyar** [ton-blockchain/intellij-ton#117]
**v1.0.3**
![image](https://github.com/ton-blockchain/intellij-ton/assets/761285/7d65dc82-f30d-4aec-852d-8d7d664c065e)

**v2.0-SNAPSHOT+18**
![image](https://github.com/ton-blockchain/intellij-ton/assets/761285/a0f57d6e-90b6-407e-9a61-fd81971b92fc)

**Comment by MicroNovaX** [comment]
Connect stdlib via include.
@andreypfau need tip about this.

**Comment by andreypfau** [comment]
The previous version of the plugin did an "implicit" include of all project files. Since in new versions of FunC it is possible to set an explicit #include, then from plugin version 2.0 you need to specify #include explicitly for the correct resolution of references

**Comment by andreypfau** [comment]
Fixed in 2.1.0
