### ISSUE TITLE
(2.0) method_id complete

### ISSUE THREAD

**Issue by MicroNovaX** [ton-blockchain/intellij-ton#126]
Need add support autocomplete in method_id modifier.
<img width="325" alt="image" src="https://github.com/ton-blockchain/intellij-ton/assets/23459010/edeab892-71f1-4f86-aaa8-db1dd9f9f777">
<img width="254" alt="image" src="https://github.com/ton-blockchain/intellij-ton/assets/23459010/80ad668a-4dd5-42d5-afd3-a01ca3984dda">

**Comment by andreypfau** [comment]
Fixed in 2.1.0
