### ISSUE TITLE
Lags appers in the Webstorm IDE while using TON 2.0 highlight for Tact files

### ISSUE THREAD

**Issue by reveloper** [ton-blockchain/intellij-ton#130]
To reproduce:
1. Open any tact - based project.
2. While opened .ts files only, have no issues with IDE UI.
3. Once .tact file opened lags appears.

<img width="1391" alt="Screenshot 2023-08-29 at 14 10 35" src="https://github.com/ton-blockchain/intellij-ton/assets/39581753/713f18a8-f330-43e2-a102-17c8d946d643">

**Comment by andreypfau** [comment]
Which version of WebStorm? Can't reproduce on 2023.2

**Comment by reveloper** [comment]
@andreypfau It was 2023.1, but the current version has no such problem, and I can't reproduce too.
<img width="434" alt="Screenshot 2023-10-03 at 01 13 23" src="https://github.com/ton-blockchain/intellij-ton/assets/39581753/a454d432-51fe-4fc0-ba7b-b516332b37b0">
