### ISSUE TITLE
Function parameter name hints for var arguments of same name

### ISSUE THREAD

**Issue by Skydev0h** [ton-blockchain/intellij-ton#167]
Inlay function parameter name hints are displayed even if the provided argument is a variable of the same name as the parameter.

Example:
![image](https://github.com/ton-blockchain/intellij-ton/assets/5331782/0a788d4a-bf87-4bd4-b8aa-3578db18f10e)

Usually, in such case, they are hidden,.

**Comment by andreypfau** [comment]
Fixed in 2.2.0
