### ISSUE TITLE
A bug with comment/uncomment already commented lines

### ISSUE THREAD

**Issue by unserialize** [ton-blockchain/intellij-ton#169]
I often select a piece of code an comment it with a hotkey.

Consider having the following initial code (note, that one line is commented already):
```
(int) main() {
;;    int a = 0;
    return 0;
}
```

I select it, press comment, and get an expected result:
```
;;(int) main() {
;;;;    int a = 0;
;;    return 0;
;;}
```

Then I want to rollback it. I select, press comment again. 

**Expected**: getting the initial code.
**Actual**:
```
(int) main() {
;    int a = 0;
    return 0;
}
```
(three ';' were removed instead of two)

**Comment by andreypfau** [comment]
Fixed in 2.2.0
