### ISSUE TITLE
Warn about dangerous FunC compiler code removal

### ISSUE THREAD

**Issue by nns2009** [ton-blockchain/intellij-ton#17]
FunC compiler may remove "impure" code.

Practically:
a) "impure" modifier present - guarantees correct behaviour
b) "impure" modifier absent - FunC compiler will do strange things, such as strip out some code without your permission.

It will silently remove the function call in two cases:

a) function returns nothing:
```
() fun() { set_data(begin_cell().end_cell()); }
```
b) function returns something, but this something is not assigned to anything:
```
(int) fun() { set_data(begin_cell().end_cell()); return 5; } 
...
int a = fun(); ;; fun is called
fun(); ;; fun call is removed
```

This is a **very bad** behavior of FunC compiler, which should be altered. It is ideal to change FunC compiler itself, but that is how it is for now, and it will be good to warn plugin users by highlighting code, which is going to be stripped by the compiler.

**Comment by tvorogme** [comment]
+1, very needed feature

**Comment by andreypfau** [comment]
It looks the same as implemented for suspend-functions in Kotlin:

![idea64_1cA4itjEwh](https://user-images.githubusercontent.com/97797573/165521981-48a87c82-8ef3-4691-9e33-43c8421b0cce.png)

But, since calling the impure function is not a compilation error, we can do it simply as an inspection-warning

**Comment by andreypfau** [comment]
Also need add quick-fix action for addition `impure` for current function like in Kotlin:
![idea64_lnTJ0iNHNC](https://user-images.githubusercontent.com/97797573/165523167-4b9cf251-a255-4aaf-bda0-ec87edcb6304.png)

**Comment by andreypfau** [comment]
Also need add warn about redundant `impure` modifier like in Kotlin `suspend`
![image](https://user-images.githubusercontent.com/97797573/165530440-b92efcca-f4f8-40fe-8f66-acbd1532425c.png)

**Comment by andreypfau** [comment]
Requires backport to 2.0

**Comment by neuroglek** [comment]
🔥

**Comment by neuroglek** [comment]
Wow
