### ISSUE TITLE
tact erros: `Unresolved reference: toCell`, `Type mismatch expected Bool, found Int`, `Unresolved reference: require ` and `Unresolved reference: ton`

### ISSUE THREAD

**Issue by kolirt** [ton-blockchain/intellij-ton#173]
Why i have these errors in tact fiels?

![image](https://github.com/ton-blockchain/intellij-ton/assets/11573343/3b97da40-3e5a-4941-be0a-2f594d81a3a6)
![image](https://github.com/ton-blockchain/intellij-ton/assets/11573343/a792c6da-870d-4b30-88ac-adf4129d5401)
![image](https://github.com/ton-blockchain/intellij-ton/assets/11573343/0cd721bc-36a8-4728-a415-b45c7d71380e)
![image](https://github.com/ton-blockchain/intellij-ton/assets/11573343/3dbd1b18-71b3-4fe6-b1b8-14bdc8c27226)

**Comment by andreypfau** [comment]
https://github.com/tact-lang/tact/issues/293

**Comment by andreypfau** [comment]
About false-positives in type checking, its still have some bugs, you can disable it in "Inspections":
<img width="999" alt="image" src="https://github.com/ton-blockchain/intellij-ton/assets/97797573/d7e03efd-89cb-4961-8eaa-50eaaec5c69c">
