### ISSUE TITLE
Autocomplete global variables

### ISSUE THREAD

**Issue by pyAndr3w** [ton-blockchain/intellij-ton#27]
Adding auto-completion for global variables in smart-contract files. Now it can autocomplete, but only in the file where the variable was defined and without understanding that it is a variable.
![image](https://user-images.githubusercontent.com/43111428/170019770-f7dd7444-2d03-4aad-b5b1-14a6475b57ae.png)

**Comment by andreypfau** [comment]
Fixed in 2.0
