### ISSUE TITLE
auto indent is broken

### ISSUE THREAD

**Issue by Naltox** [ton-blockchain/intellij-ton#38]
Expected behaviour: 

<img width="493" alt="Screenshot 2022-08-04 at 01 37 35" src="https://user-images.githubusercontent.com/8849761/182724350-43ba7faa-2d50-4602-995c-18d214cad96a.png">

Actual behaviour: 

<img width="502" alt="Screenshot 2022-08-04 at 01 38 10" src="https://user-images.githubusercontent.com/8849761/182724412-596cca30-b5d0-45c2-96b0-e2eb86c83879.png">

**Comment by andreypfau** [comment]
Fixed in 2.1.0
