### ISSUE TITLE
Improvement of code reformat

### ISSUE THREAD

**Issue by tvorogme** [ton-blockchain/intellij-ton#45]
![image](https://user-images.githubusercontent.com/19264196/188609235-86e08648-dae1-43c2-af47-c1e5b12a1564.png)

Suggest to improve code reformat in `if / else` conditions. Will be great :heart:

**Comment by andreypfau** [comment]
Is it actual on 2.0.2?

**Comment by andreypfau** [comment]
Not actual in 2.0+
