### ISSUE TITLE
Not all function arguments have pretty name helper

### ISSUE THREAD

**Issue by tvorogme** [ton-blockchain/intellij-ton#55]
<img width="646" alt="Screen Shot 2022-11-11 at 1 29 20 PM" src="https://user-images.githubusercontent.com/19264196/201321615-a02a539c-8e36-4d4e-9e7b-dcc6aef0956b.png">

**Comment by andreypfau** [comment]
This is not a bug - this behavior happens in other languages too (it is assumed that named variables do not require hints)

**Comment by andreypfau** [comment]
fixed in 2.0
