### ISSUE TITLE
Add support for multiline asm functions in the FunC

### ISSUE THREAD

**Issue by pyAndr3w** [ton-blockchain/intellij-ton#80]
Plugin currently doesn't support multiline asm functions using triple quotes (""""). Example:
```python
slice hello_world() asm """
  "Hello"
  " "
  "World"
  $+ $+ $>s
  PUSHSLICE
""";
```

[Docs](https://ton.org/docs/develop/func/functions#multiline-asms)

**Comment by pyAndr3w** [comment]
At the moment it looks like this.
![image](https://user-images.githubusercontent.com/43111428/225618574-1114282e-1a02-4d76-bc72-f44c62c25269.png)

**Comment by andreypfau** [comment]
Support for multiline strings coming soon in version 2.0
<img width="600" alt="image" src="https://github.com/ton-blockchain/intellij-ton/assets/97797573/ecd1f833-affb-4098-be0d-10094c2a856e">
